# Generated by Django 4.0.1 on 2023-01-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceApp', '0002_cart_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='productId',
        ),
    ]
